# Generated by Django 5.2.4 on 2025-08-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='job_title',
            new_name='job',
        ),
    ]
