# Generated by Django 5.2.4 on 2025-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_job_title_vacancy_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_developer', models.CharField(choices=[('backend', 'Backend разработчик'), ('frontend', 'Frontend разработчик'), ('devops', 'DevOps инженер'), ('uiux', 'UI/UX дизайнер')], max_length=20, verbose_name='Choose position')),
                ('work_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('online', 'Удалённая работа')], max_length=20, verbose_name='Work type')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Resume / CV')),
            ],
            options={
                'verbose_name': 'Job application',
                'verbose_name_plural': 'Job applications',
            },
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job',
            field=models.CharField(max_length=250, verbose_name='Job title'),
        ),
    ]
