# Generated by Django 5.2.4 on 2025-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_jobapplication_alter_vacancy_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='work_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('online', 'Online')], max_length=20, verbose_name='Work type'),
        ),
    ]
