# Generated by Django 5.2.4 on 2025-08-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_jobapplication_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('position', models.CharField(max_length=150, verbose_name='Position')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('image', models.ImageField(upload_to='client_images/', verbose_name='Client Image')),
                ('feedback_file', models.FileField(upload_to='feedback_files/', verbose_name='Feedback File')),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedbacks',
            },
        ),
    ]
