# Generated by Django 5.2.4 on 2025-08-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_clientfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='comment_en',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='comment_ru',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='comment_uz',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
    ]
