# Generated by Django 5.2.4 on 2025-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_clientfeedback_comment_en_clientfeedback_comment_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='company_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='company_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='company_name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='position_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='position_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='position_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Position'),
        ),
    ]
